; generated by PrusaSlicer 2.7.1+MacOS-x64 on 2024-02-08 at 22:30:14 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.70mm

M104 S200 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
G1 Z.35 F7800
G1 E-2 F2400
G92 E0
G1 X82.415 Y83.253 F7800
G1 E2 F2400
;TYPE:Skirt/Brim
;WIDTH:0.7
G1 F1800
G1 X84.168 Y81.774 E2.20855
G1 X86.32 Y80.981 E2.41709
G1 X87.5 Y80.875 E2.52482
G1 X112.5 Y80.875 E4.79806
G1 X114.759 Y81.272 E5.00662
G1 X116.747 Y82.415 E5.21514
G1 X118.226 Y84.168 E5.42369
G1 X119.019 Y86.32 E5.63223
G1 X119.125 Y87.5 E5.73996
G1 X119.125 Y112.5 E8.0132
G1 X118.728 Y114.759 E8.22176
G1 X117.585 Y116.747 E8.43028
G1 X115.832 Y118.226 E8.63883
G1 X113.68 Y119.019 E8.84737
G1 X112.5 Y119.125 E8.9551
G1 X87.5 Y119.125 E11.22834
G1 X85.241 Y118.728 E11.4369
G1 X83.253 Y117.585 E11.64542
G1 X81.774 Y115.832 E11.85397
G1 X80.981 Y113.68 E12.06251
G1 X80.875 Y112.5 E12.17024
G1 X80.875 Y87.5 E14.44348
G1 X81.272 Y85.241 E14.65204
G1 X82.386 Y83.305 E14.85514
G1 E12.85514 F2400
G92 E0
G1 X82.386 Y83.305 F7800
G1 X110.9 Y110.9
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:0.7
G1 F1800
G1 X89.1 Y110.9 E3.98226
G1 X89.1 Y89.1 E5.96452
G1 X110.9 Y89.1 E7.94678
G1 X110.9 Y100 E8.93791
G1 X110.9 Y110.84 E9.92359
G1 X111.525 Y111.525 F7800
G1 F1800
G1 X88.475 Y111.525 E12.01952
G1 X88.475 Y88.475 E14.11545
G1 X111.525 Y88.475 E16.21138
G1 X111.525 Y100 E17.25934
G1 X111.525 Y111.465 E18.30185
G1 X112.15 Y112.15 F7800
;TYPE:External perimeter
G1 F1800
G1 X87.85 Y112.15 E20.51144
G1 X87.85 Y87.85 E22.72103
G1 X112.15 Y87.85 E24.93062
G1 X112.15 Y100 E26.03541
G1 X112.15 Y112.09 E27.13475
G1 X111.754 Y112.149 F7800
G1 E25.13475 F2400
G92 E0
G1 X109.432 Y89.287 F7800
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:0.708207
G1 F1800
G1 X110.432 Y90.287 E2.13028
G1 X110.432 Y91.182 E2.21273
G1 X108.818 Y89.568 E2.42301
G1 X107.923 Y89.568 E2.50546
G1 X110.432 Y92.077 E2.83234
G1 X110.432 Y92.973 E2.91488
G1 X107.027 Y89.568 E3.35849
G1 X106.132 Y89.568 E3.44094
G1 X110.432 Y93.868 E4.00116
G1 X110.432 Y94.763 E4.08361
G1 X105.237 Y89.568 E4.76043
G1 X104.341 Y89.568 E4.84297
G1 X110.432 Y95.659 E5.63652
G1 X110.432 Y96.554 E5.71897
G1 X103.446 Y89.568 E6.62912
G1 X102.551 Y89.568 E6.71157
G1 X110.432 Y97.449 E7.73833
G1 X110.432 Y98.345 E7.82087
G1 X101.655 Y89.568 E8.96436
G1 X100.76 Y89.568 E9.04681
G1 X110.432 Y99.24 E10.3069
G1 X110.432 Y100.135 E10.38935
G1 X99.865 Y89.568 E11.76605
G1 X98.969 Y89.568 E11.84859
G1 X110.432 Y101.031 E13.34202
G1 X110.432 Y101.926 E13.42447
G1 X98.074 Y89.568 E15.0345
G1 X97.179 Y89.568 E15.11695
G1 X110.432 Y102.821 E16.84359
G1 X110.432 Y103.717 E16.92613
G1 X96.283 Y89.568 E18.7695
G1 X95.388 Y89.568 E18.85195
G1 X110.432 Y104.612 E20.81192
G1 X110.432 Y105.507 E20.89437
G1 X94.493 Y89.568 E22.97095
G1 X93.597 Y89.568 E23.05349
G1 X110.432 Y106.403 E25.2468
G1 X110.432 Y107.298 E25.32925
G1 X92.702 Y89.568 E27.63916
G1 X91.807 Y89.568 E27.72161
G1 X110.432 Y108.193 E30.14812
G1 X110.432 Y109.089 E30.23066
G1 X90.911 Y89.568 E32.77391
G1 X90.016 Y89.568 E32.85636
G1 X110.432 Y109.984 E35.51621
G1 X110.432 Y110.432 E35.55748
G1 X109.984 Y110.432 E35.59875
G1 X89.568 Y90.016 E38.2586
G1 X89.568 Y90.912 E38.34114
G1 X109.088 Y110.432 E40.88426
G1 X108.193 Y110.432 E40.96671
G1 X89.568 Y91.807 E43.39322
G1 X89.568 Y92.702 E43.47567
G1 X107.298 Y110.432 E45.78558
G1 X106.403 Y110.432 E45.86803
G1 X89.568 Y93.598 E48.06127
G1 X89.568 Y94.493 E48.14372
G1 X105.507 Y110.432 E50.2203
G1 X104.612 Y110.432 E50.30275
G1 X89.568 Y95.388 E52.26272
G1 X89.568 Y96.284 E52.34526
G1 X103.717 Y110.432 E54.18856
G1 X102.821 Y110.432 E54.2711
G1 X89.568 Y97.179 E55.99774
G1 X89.568 Y98.074 E56.08019
G1 X101.926 Y110.432 E57.69022
G1 X101.031 Y110.432 E57.77267
G1 X89.568 Y98.97 E59.26603
G1 X89.568 Y99.865 E59.34848
G1 X100.135 Y110.432 E60.72518
G1 X99.24 Y110.432 E60.80763
G1 X89.568 Y100.76 E62.06772
G1 X89.568 Y101.655 E62.15017
G1 X98.345 Y110.432 E63.29366
G1 X97.449 Y110.432 E63.3762
G1 X89.568 Y102.551 E64.40296
G1 X89.568 Y103.446 E64.48541
G1 X96.554 Y110.432 E65.39556
G1 X95.659 Y110.432 E65.47801
G1 X89.568 Y104.341 E66.27156
G1 X89.568 Y105.237 E66.3541
G1 X94.763 Y110.432 E67.03092
G1 X93.868 Y110.432 E67.11337
G1 X89.568 Y106.132 E67.67359
G1 X89.568 Y107.027 E67.75604
G1 X92.973 Y110.432 E68.19965
G1 X92.077 Y110.432 E68.28219
G1 X89.568 Y107.923 E68.60907
G1 X89.568 Y108.818 E68.69152
G1 X91.182 Y110.432 E68.9018
G1 X90.287 Y110.432 E68.98425
G1 X89.287 Y109.432 E69.11453
;LAYER_CHANGE
;Z:0.65
;HEIGHT:0.3
G1 Z.65 F7800
G1 E67.11453 F2400
G92 E0
G1 X89.287 Y109.432 F7800
G1 X111.504 Y111.504
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:0.45
G1 F3600
G1 X88.496 Y111.504 E3.1066
G1 X88.496 Y88.496 E4.2132
G1 X111.504 Y88.496 E5.3198
G1 X111.504 Y100 E5.8731
G1 X111.504 Y111.444 E6.42352
G1 X111.889 Y111.889 F7800
G1 F3600
G1 X88.111 Y111.889 E7.56716
G1 X88.111 Y88.111 E8.7108
G1 X111.889 Y88.111 E9.85444
G1 X111.889 Y100 E10.42626
G1 X111.889 Y111.829 E10.99519
G1 X112.275 Y112.275 F7800
;TYPE:External perimeter
G1 F1800
G1 X87.725 Y112.275 E12.17596
G1 X87.725 Y87.725 E13.35673
G1 X112.275 Y87.725 E14.5375
G1 X112.275 Y100 E15.12788
G1 X112.275 Y112.215 E15.71538
G1 X111.879 Y112.274 F7800
G1 E13.71538 F2400
G92 E0
G1 X88.89 Y88.817 F7800
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:0.543559
G1 F1200
G1 X88.848 Y88.774 E2.00359
G1 X88.79 Y88.79 E2.00719
G1 X88.774 Y88.848 E2.01079
G1 X88.817 Y88.89 E2.01438
G1 X88.875 Y88.875 E2.01796
;WIDTH:0.45
G1 X88.785 Y89.491 E2.0479
G1 X89.491 Y88.785 E2.09592
G1 X90.036 Y88.785 E2.12213
G1 X88.785 Y90.036 E2.20722
G1 X88.785 Y90.581 E2.23343
G1 X90.581 Y88.785 E2.35559
G1 X91.127 Y88.785 E2.38185
G1 X88.785 Y91.127 E2.54115
G1 X88.785 Y91.672 E2.56736
G1 X91.672 Y88.785 E2.76373
G1 X92.217 Y88.785 E2.78994
G1 X88.785 Y92.217 E3.02338
G1 X88.785 Y92.763 E3.04964
G1 X92.763 Y88.785 E3.32022
G1 X93.308 Y88.785 E3.34643
G1 X88.785 Y93.308 E3.65408
G1 X88.785 Y93.853 E3.68029
G1 X93.853 Y88.785 E4.02501
G1 X94.399 Y88.785 E4.05127
G1 X88.785 Y94.399 E4.43313
G1 X88.785 Y94.944 E4.45934
G1 X94.944 Y88.785 E4.87827
G1 X95.489 Y88.785 E4.90448
G1 X88.785 Y95.489 E5.36048
G1 X88.785 Y96.035 E5.38674
G1 X96.035 Y88.785 E5.87988
G1 X96.58 Y88.785 E5.90609
G1 X88.785 Y96.58 E6.4363
G1 X88.785 Y97.125 E6.46251
G1 X97.125 Y88.785 E7.02979
G1 X97.671 Y88.785 E7.05605
G1 X88.785 Y97.671 E7.66046
G1 X88.785 Y98.216 E7.68667
G1 X98.216 Y88.785 E8.32815
G1 X98.761 Y88.785 E8.35436
G1 X88.785 Y98.761 E9.03292
G1 X88.785 Y99.307 E9.05918
G1 X99.307 Y88.785 E9.77487
G1 X99.852 Y88.785 E9.80108
G1 X88.785 Y99.852 E10.55384
G1 X88.785 Y100.397 E10.58005
G1 X100.397 Y88.785 E11.36988
G1 X100.943 Y88.785 E11.39614
G1 X88.785 Y100.943 E12.22311
G1 X88.785 Y101.488 E12.24932
G1 X101.488 Y88.785 E13.11336
G1 X102.034 Y88.785 E13.13962
G1 X88.785 Y102.034 E14.0408
G1 X88.785 Y102.579 E14.06701
G1 X102.579 Y88.785 E15.00526
G1 X103.124 Y88.785 E15.03147
G1 X88.785 Y103.124 E16.00679
G1 X88.785 Y103.67 E16.03305
G1 X103.67 Y88.785 E17.04551
G1 X104.215 Y88.785 E17.07172
G1 X88.785 Y104.215 E18.12125
G1 X88.785 Y104.76 E18.14746
G1 X104.76 Y88.785 E19.23406
G1 X105.306 Y88.785 E19.26032
G1 X88.785 Y105.306 E20.38406
G1 X88.785 Y105.851 E20.41027
G1 X105.851 Y88.785 E21.57108
G1 X106.396 Y88.785 E21.59729
G1 X88.785 Y106.396 E22.79517
G1 X88.785 Y106.942 E22.82143
G1 X106.942 Y88.785 E24.05645
G1 X107.487 Y88.785 E24.08266
G1 X88.785 Y107.487 E25.35475
G1 X88.785 Y108.032 E25.38096
G1 X108.032 Y88.785 E26.69012
G1 X108.578 Y88.785 E26.71638
G1 X88.785 Y108.578 E28.06268
G1 X88.785 Y109.123 E28.08889
G1 X109.123 Y88.785 E29.47226
G1 X109.668 Y88.785 E29.49847
G1 X88.785 Y109.668 E30.91891
G1 X88.785 Y110.214 E30.94517
G1 X110.214 Y88.785 E32.40274
G1 X110.759 Y88.785 E32.42895
G1 X88.785 Y110.759 E33.92359
G1 X88.705 Y111.325 E33.95108
;WIDTH:0.404381
G1 X88.634 Y111.306 E33.9542
G1 X88.653 Y111.377 E33.95732
G1 X88.694 Y111.366 E33.95912
;WIDTH:0.45
G1 X88.875 Y111.215 E33.97046
G1 X111.215 Y88.875 E35.49
G1 X111.366 Y88.694 E35.50134
;WIDTH:0.404381
G1 X111.325 Y88.705 E35.50314
G1 X111.306 Y88.634 E35.50626
G1 X111.377 Y88.653 E35.50938
G1 X111.215 Y89.421 F7800
;WIDTH:0.45
G1 F1200
G1 X89.421 Y111.215 E36.99178
G1 X89.966 Y111.215 E37.01799
G1 X111.215 Y89.966 E38.46332
G1 X111.215 Y90.511 E38.48953
G1 X90.511 Y111.215 E39.89779
G1 X91.057 Y111.215 E39.92405
G1 X111.215 Y91.057 E41.29517
G1 X111.215 Y91.602 E41.32138
G1 X91.602 Y111.215 E42.65543
G1 X92.147 Y111.215 E42.68164
G1 X111.215 Y92.147 E43.97862
G1 X111.215 Y92.693 E44.00488
G1 X92.693 Y111.215 E45.26472
G1 X93.238 Y111.215 E45.29093
G1 X111.215 Y93.238 E46.5137
G1 X111.215 Y93.783 E46.53991
G1 X93.783 Y111.215 E47.72561
G1 X94.329 Y111.215 E47.75187
G1 X111.215 Y94.329 E48.90043
G1 X111.215 Y94.874 E48.92664
G1 X94.874 Y111.215 E50.03813
G1 X95.42 Y111.215 E50.06439
G1 X111.215 Y95.42 E51.13875
G1 X111.215 Y95.965 E51.16496
G1 X95.965 Y111.215 E52.20225
G1 X96.51 Y111.215 E52.22846
G1 X111.215 Y96.51 E53.22868
G1 X111.215 Y97.056 E53.25494
G1 X97.056 Y111.215 E54.21802
G1 X97.601 Y111.215 E54.24423
G1 X111.215 Y97.601 E55.17024
G1 X111.215 Y98.146 E55.19645
G1 X98.146 Y111.215 E56.08539
G1 X98.692 Y111.215 E56.11165
G1 X111.215 Y98.692 E56.96345
G1 X111.215 Y99.237 E56.98966
G1 X99.237 Y111.215 E57.80439
G1 X99.782 Y111.215 E57.8306
G1 X111.215 Y99.782 E58.60826
G1 X111.215 Y100.328 E58.63452
G1 X100.328 Y111.215 E59.37504
G1 X100.873 Y111.215 E59.40125
G1 X111.215 Y100.873 E60.1047
G1 X111.215 Y101.418 E60.13091
G1 X101.418 Y111.215 E60.79729
G1 X101.964 Y111.215 E60.82355
G1 X111.215 Y101.964 E61.45279
G1 X111.215 Y102.509 E61.479
G1 X102.509 Y111.215 E62.07117
G1 X103.054 Y111.215 E62.09738
G1 X111.215 Y103.054 E62.65248
G1 X111.215 Y103.6 E62.67874
G1 X103.6 Y111.215 E63.1967
G1 X104.145 Y111.215 E63.22291
G1 X111.215 Y104.145 E63.7038
G1 X111.215 Y104.69 E63.73001
G1 X104.69 Y111.215 E64.17383
G1 X105.236 Y111.215 E64.20009
G1 X111.215 Y105.236 E64.60677
G1 X111.215 Y105.781 E64.63298
G1 X105.781 Y111.215 E65.00259
G1 X106.326 Y111.215 E65.0288
G1 X111.215 Y106.326 E65.36134
G1 X111.215 Y106.872 E65.3876
G1 X106.872 Y111.215 E65.68301
G1 X107.417 Y111.215 E65.70922
G1 X111.215 Y107.417 E65.96756
G1 X111.215 Y107.963 E65.99382
G1 X107.963 Y111.215 E66.21502
G1 X108.508 Y111.215 E66.24123
G1 X111.215 Y108.508 E66.42536
G1 X111.215 Y109.053 E66.45157
G1 X109.053 Y111.215 E66.59863
G1 X109.599 Y111.215 E66.62489
G1 X111.215 Y109.599 E66.73481
G1 X111.215 Y110.144 E66.76102
G1 X110.144 Y111.215 E66.83387
G1 X110.689 Y111.215 E66.86008
G1 X111.215 Y110.689 E66.89586
G1 X111.409 Y110.571 E66.90678
;WIDTH:0.404381
G1 X111.368 Y110.582 E66.90858
G1 X111.349 Y110.511 E66.9117
G1 X111.42 Y110.53 E66.91482
;LAYER_CHANGE
;Z:0.95
;HEIGHT:0.3
G1 Z.95 F7800
G1 X111.504 Y111.504
;TYPE:Perimeter
;WIDTH:0.45
G1 F3600
G1 X88.496 Y111.504 E68.02142
G1 X88.496 Y88.496 E69.12802
G1 X111.504 Y88.496 E70.23462
G1 X111.504 Y100 E70.78792
G1 X111.504 Y111.444 E71.33834
G1 X111.889 Y111.889 F7800
G1 F3600
G1 X88.111 Y111.889 E72.48198
G1 X88.111 Y88.111 E73.62562
G1 X111.889 Y88.111 E74.76926
G1 X111.889 Y100 E75.34108
G1 X111.889 Y111.829 E75.91001
G1 X112.275 Y112.275 F7800
;TYPE:External perimeter
G1 F1800
G1 X87.725 Y112.275 E77.09078
G1 X87.725 Y87.725 E78.27155
G1 X112.275 Y87.725 E79.45232
G1 X112.275 Y100 E80.0427
G1 X112.275 Y112.215 E80.6302
G1 X111.879 Y112.274 F7800
G1 E78.6302 F2400
G92 E0
G1 X110.711 Y88.609 F7800
G1 E2 F2400
;TYPE:Top solid infill
;WIDTH:0.400473
G1 F900
G1 X111.24 Y89.138 E2.03136
G1 X111.24 Y89.613 E2.05127
G1 X110.387 Y88.76 E2.10184
G1 X109.912 Y88.76 E2.12175
G1 X111.24 Y90.088 E2.20048
G1 X111.24 Y90.564 E2.22043
G1 X109.436 Y88.76 E2.32738
G1 X108.961 Y88.76 E2.34729
G1 X111.24 Y91.039 E2.4824
G1 X111.24 Y91.514 E2.50231
G1 X108.486 Y88.76 E2.66557
G1 X108.01 Y88.76 E2.68552
G1 X111.24 Y91.99 E2.877
G1 X111.24 Y92.465 E2.89691
G1 X107.535 Y88.76 E3.11655
G1 X107.06 Y88.76 E3.13646
G1 X111.24 Y92.94 E3.38426
G1 X111.24 Y93.416 E3.40421
G1 X106.584 Y88.76 E3.68023
G1 X106.109 Y88.76 E3.70014
G1 X111.24 Y93.891 E4.00432
G1 X111.24 Y94.366 E4.02423
G1 X105.634 Y88.76 E4.35657
G1 X105.158 Y88.76 E4.37652
G1 X111.24 Y94.842 E4.73708
G1 X111.24 Y95.317 E4.75699
G1 X104.683 Y88.76 E5.14571
G1 X104.208 Y88.76 E5.16562
G1 X111.24 Y95.792 E5.5825
G1 X111.24 Y96.267 E5.60241
G1 X103.733 Y88.76 E6.04745
G1 X103.257 Y88.76 E6.0674
G1 X111.24 Y96.743 E6.54065
G1 X111.24 Y97.218 E6.56056
G1 X102.782 Y88.76 E7.06197
G1 X102.307 Y88.76 E7.08188
G1 X111.24 Y97.693 E7.61145
G1 X111.24 Y98.169 E7.6314
G1 X101.831 Y88.76 E8.18919
G1 X101.356 Y88.76 E8.2091
G1 X111.24 Y98.644 E8.79505
G1 X111.24 Y99.119 E8.81496
G1 X100.881 Y88.76 E9.42907
G1 X100.405 Y88.76 E9.44902
G1 X111.24 Y99.595 E10.09135
G1 X111.24 Y100.07 E10.11126
G1 X99.93 Y88.76 E10.78175
G1 X99.455 Y88.76 E10.80166
G1 X111.24 Y100.545 E11.50031
G1 X111.24 Y101.021 E11.52026
G1 X98.979 Y88.76 E12.24713
G1 X98.504 Y88.76 E12.26704
G1 X111.24 Y101.496 E13.02207
G1 X111.24 Y101.971 E13.04198
G1 X98.029 Y88.76 E13.82516
G1 X97.554 Y88.76 E13.84507
G1 X111.24 Y102.446 E14.65641
G1 X111.24 Y102.922 E14.67636
G1 X97.078 Y88.76 E15.51592
G1 X96.603 Y88.76 E15.53583
G1 X111.24 Y103.397 E16.40355
G1 X111.24 Y103.872 E16.42346
G1 X96.128 Y88.76 E17.31934
G1 X95.652 Y88.76 E17.33929
G1 X111.24 Y104.348 E18.26339
G1 X111.24 Y104.823 E18.2833
G1 X95.177 Y88.76 E19.23556
G1 X94.702 Y88.76 E19.25547
G1 X111.24 Y105.298 E20.23589
G1 X111.24 Y105.774 E20.25584
G1 X94.226 Y88.76 E21.26448
G1 X93.751 Y88.76 E21.28439
G1 X111.24 Y106.249 E22.32119
G1 X111.24 Y106.724 E22.3411
G1 X93.276 Y88.76 E23.40606
G1 X92.801 Y88.76 E23.42597
G1 X111.24 Y107.199 E24.51908
G1 X111.24 Y107.675 E24.53903
G1 X92.325 Y88.76 E25.66036
G1 X91.85 Y88.76 E25.68027
G1 X111.24 Y108.15 E26.82976
G1 X111.24 Y108.625 E26.84967
G1 X91.375 Y88.76 E28.02732
G1 X90.899 Y88.76 E28.04727
G1 X111.24 Y109.101 E29.25314
G1 X111.24 Y109.576 E29.27305
G1 X90.424 Y88.76 E30.50708
G1 X89.949 Y88.76 E30.52699
G1 X111.24 Y110.051 E31.78918
G1 X111.24 Y110.527 E31.80913
G1 X89.473 Y88.76 E33.09954
G1 X88.998 Y88.76 E33.11945
G1 X111.24 Y111.002 E34.43802
G1 X111.24 Y111.24 E34.448
G1 X111.002 Y111.24 E34.45798
G1 X88.76 Y88.998 E35.77655
G1 X88.76 Y89.473 E35.79646
G1 X110.527 Y111.24 E37.08687
G1 X110.051 Y111.24 E37.10682
G1 X88.76 Y89.949 E38.36901
G1 X88.76 Y90.424 E38.38892
G1 X109.576 Y111.24 E39.62295
G1 X109.101 Y111.24 E39.64286
G1 X88.76 Y90.899 E40.84873
G1 X88.76 Y91.375 E40.86868
G1 X108.625 Y111.24 E42.04633
G1 X108.15 Y111.24 E42.06624
G1 X88.76 Y91.85 E43.21573
G1 X88.76 Y92.325 E43.23564
G1 X107.675 Y111.24 E44.35697
G1 X107.199 Y111.24 E44.37692
G1 X88.76 Y92.801 E45.47003
G1 X88.76 Y93.276 E45.48994
G1 X106.724 Y111.24 E46.5549
G1 X106.249 Y111.24 E46.57481
G1 X88.76 Y93.751 E47.61161
G1 X88.76 Y94.227 E47.63156
G1 X105.773 Y111.24 E48.64014
G1 X105.298 Y111.24 E48.66005
G1 X88.76 Y94.702 E49.64047
G1 X88.76 Y95.177 E49.66038
G1 X104.823 Y111.24 E50.61264
G1 X104.348 Y111.24 E50.63255
G1 X88.76 Y95.652 E51.55665
G1 X88.76 Y96.128 E51.5766
G1 X103.872 Y111.24 E52.47248
G1 X103.397 Y111.24 E52.49239
G1 X88.76 Y96.603 E53.36011
G1 X88.76 Y97.078 E53.38002
G1 X102.922 Y111.24 E54.21958
G1 X102.446 Y111.24 E54.23953
G1 X88.76 Y97.554 E55.05087
G1 X88.76 Y98.029 E55.07078
G1 X101.971 Y111.24 E55.85396
G1 X101.496 Y111.24 E55.87387
G1 X88.76 Y98.504 E56.6289
G1 X88.76 Y98.98 E56.64885
G1 X101.02 Y111.24 E57.37566
G1 X100.545 Y111.24 E57.39557
G1 X88.76 Y99.455 E58.09422
G1 X88.76 Y99.93 E58.11413
G1 X100.07 Y111.24 E58.78462
G1 X99.595 Y111.24 E58.80453
G1 X88.76 Y100.405 E59.44686
G1 X88.76 Y100.881 E59.46681
G1 X99.119 Y111.24 E60.08092
G1 X98.644 Y111.24 E60.10083
G1 X88.76 Y101.356 E60.68678
G1 X88.76 Y101.831 E60.70669
G1 X98.169 Y111.24 E61.26448
G1 X97.693 Y111.24 E61.28443
G1 X88.76 Y102.307 E61.814
G1 X88.76 Y102.782 E61.83391
G1 X97.218 Y111.24 E62.33532
G1 X96.743 Y111.24 E62.35523
G1 X88.76 Y103.257 E62.82848
G1 X88.76 Y103.733 E62.84843
G1 X96.267 Y111.24 E63.29347
G1 X95.792 Y111.24 E63.31338
G1 X88.76 Y104.208 E63.73026
G1 X88.76 Y104.683 E63.75017
G1 X95.317 Y111.24 E64.13889
G1 X94.841 Y111.24 E64.15884
G1 X88.76 Y105.159 E64.51934
G1 X88.76 Y105.634 E64.53925
G1 X94.366 Y111.24 E64.87159
G1 X93.891 Y111.24 E64.8915
G1 X88.76 Y106.109 E65.19568
G1 X88.76 Y106.584 E65.21559
G1 X93.416 Y111.24 E65.49161
G1 X92.94 Y111.24 E65.51156
G1 X88.76 Y107.06 E65.75936
G1 X88.76 Y107.535 E65.77927
G1 X92.465 Y111.24 E65.99891
G1 X91.99 Y111.24 E66.01882
G1 X88.76 Y108.01 E66.2103
G1 X88.76 Y108.486 E66.23025
G1 X91.514 Y111.24 E66.39351
G1 X91.039 Y111.24 E66.41342
G1 X88.76 Y108.961 E66.54853
G1 X88.76 Y109.436 E66.56844
G1 X90.564 Y111.24 E66.67539
G1 X90.088 Y111.24 E66.69534
G1 X88.76 Y109.912 E66.77407
G1 X88.76 Y110.387 E66.79398
G1 X89.613 Y111.24 E66.84455
G1 X89.138 Y111.24 E66.86446
G1 X88.609 Y110.711 E66.89582
G1 E64.89582 F2400
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 262.35
; filament used [cm3] = 0.63
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 3m 50s
; estimated first layer printing time (normal mode) = 42s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "- default -"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 20%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_height = 0.35
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = reprap
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.3
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 35
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = - default -
; printer_model = 
; printer_notes = 
; printer_settings_id = - default FFF -
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
end_end